Brandon/remove button
radicle-dev/radicle.foundation pull request #1
Opened 2021-04-09 09:05 UTC by brandonhaslegs

Julien thought the button looked better as a link

2021-04-09 09:19 UTC, cloudhead requested changes
Will take a look at the new design in a bit

2021-04-09 09:19 UTC, cloudhead commented on css/index.css
> +@import url("https://rsms.me/inter/inter.css");
I'd rather not import fonts from a third party.

2021-04-09 09:19 UTC, cloudhead commented on css/index.css
> +  --color-foreground-level-5: #d3dee8;
These can be moved to the other :root selector

2021-04-09 09:19 UTC, cloudhead commented on css/index.css
> +    font-family: "Inter var", sans-serif;
What's this for?

2021-04-09 09:24 UTC, brandonhaslegs commented on css/index.css
> +    font-family: "Inter var", sans-serif;
Instead of pulling in multiple fonts, this allows us to use the variable font feature of Inter. More on variable fonts [here](https://en.wikipedia.org/wiki/Variable_font). I wanted to add bold text in the button to the site and instead of importing a new font file, I just imported the variable font file.

Since I removed the button though, I think we can go back to just serving the single font file.

2021-04-09 09:24 UTC, brandonhaslegs commented on css/index.css
> +@import url("https://rsms.me/inter/inter.css");
Thought you might say that. That's fine, we can revert this and go back to just importing a single font file.

2021-04-09 09:53 UTC, cloudhead commented
I like the new design, but feel like the logo/header looks a bit small :shrug:

2021-04-09 09:53 UTC, cloudhead commented
I like the new design, but feel like the logo/header looks a bit small :shrug:

2021-04-09 12:48 UTC, brandonhaslegs commented on css/index.css
> +  --color-foreground-level-5: #d3dee8;
Don't know what other :root selector you mean.

2021-04-09 12:49 UTC, brandonhaslegs commented
@cloudhead Updated but not sure what you meant with moving to the other root.

2021-04-11 10:37 UTC, juliendonck commented on css/index.css
> +  --color-foreground-level-5: #d3dee8;
There were two `:root {}` selectors. Seems like you fixed it.

2021-04-11 10:37 UTC, juliendonck approved these changes

2021-04-13 15:18 UTC, cloudhead commented on index.html.template
> +        src: url("/fonts/Inter-Regular.otf");
The .otf file is still showing up as removed, while an unused .woff anf .woff2 file have been added :thinking:

2021-04-13 15:19 UTC, cloudhead commented on index.html.template
> +        src: url("/fonts/Inter-Regular.otf");
I would recommend just using the .woff and removing the .woff2, as it's not widely supported.

2021-04-13 15:20 UTC, cloudhead commented on join/index.html.template
> +      }
This root block doesn't need to live here, it can be moved to index.css

2021-04-16 11:58 UTC, juliendonck commented on index.html.template
> +        src: url("/fonts/Inter-Regular.otf");
fixed

2021-04-16 11:58 UTC, juliendonck commented on join/index.html.template
> +      }
fixed

2021-04-16 13:01 UTC, cloudhead approved these changes

2021-04-16 13:03 UTC, cloudhead commented
Merged via 7f1894a

2021-04-16 13:03 UTC, closed without merging